name: Verify Sensitive Data

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check-sensitive-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download and unpack TruffleHog
      run: |
        wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.81.0/trufflehog_3.81.0_linux_amd64.tar.gz
        tar -xzf trufflehog_3.81.0_linux_amd64.tar.gz
        chmod +x trufflehog

    - name: Run TruffleHog on config files
      run: ./trufflehog filesystem config.dev.json config.prod.json

    - name: Create log.txt with results
      run: |
        echo "ðŸ” **Checking config.dev.json and config.prod.json for sensitive data...**" > log.txt
        if grep -q "Reason" trufflehog-report.json; then
          echo "âŒ TruffleHog found issues in one of the config files" >> log.txt
        else
          echo "âœ… No issues found in config.dev.json and config.prod.json" >> log.txt
        fi

    - name: Add result as comment
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: sensitive
        recreate: true
        path: log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}