name: Verify Sensitive Data

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check-sensitive-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Gitleaks
      run: |
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz
        tar -xzf gitleaks_8.17.0_linux_x64.tar.gz
        chmod +x gitleaks

    - name: Run Gitleaks on config.dev.yml
      run: ./gitleaks detect --source=config.dev.yml --report-format=json --report-path=gitleaks-dev.json

    - name: Run Gitleaks on config.prod.yml
      run: ./gitleaks detect --source=config.prod.yml --report-format=json --report-path=gitleaks-prod.json

    - name: Create log.txt with results
      run: |
        echo "ðŸ” **Checking config.dev.yml for sensitive data...**" > log.txt
        if [ -s gitleaks-dev.json ]; then
          echo "âŒ Gitleaks found issues in config.dev.yml" >> log.txt
        else
          echo "âœ… No issues found in config.dev.yml" >> log.txt
        fi
        echo "ðŸ” **Checking config.prod.yml for sensitive data...**" >> log.txt
        if [ -s gitleaks-prod.json ]; then
          echo "âŒ Gitleaks found issues in config.prod.yml" >> log.txt
        else
          echo "âœ… No issues found in config.prod.yml" >> log.txt
        fi

    - name: Add result as comment
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: sensitive
        recreate: true
        path: log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}