name: Verify Sensitive Data

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check-sensitive-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Run Gitleaks on config.dev.yml
      run: |
        echo "ðŸ” **Checking config.dev.yml for sensitive data...**" > sens.log.txt
        gitleaks detect --source=config.dev.yml --redact >> sens.log.txt 2>&1 || echo "âŒ Gitleaks found issues in config.dev.yml" >> sens.log.txt
        echo "âœ… No issues found in config.dev.yml" >> sens.log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Gitleaks on config.prod.yml
      run: |
        echo "ðŸ” **Checking config.prod.yml for sensitive data...**" >> sens.log.txt
        gitleaks detect --source=config.prod.yml --redact >> sens.log.txt 2>&1 || echo "âŒ Gitleaks found issues in config.prod.yml" >> sens.log.txt
        echo "âœ… No issues found in config.prod.yml" >> sens.log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add check result as comment
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: sens.log.txt
        header: pull-request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        