name: Verify Sensitive Data

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  check-sensitive-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run TruffleHog on config files
      uses: trufflesecurity/trufflehog@v3
      with:
        scan: repo
        format: json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check config.dev.yml and config.prod.yml for sensitive data
      run: |
        echo "ðŸ” **Checking config.dev.yml for sensitive data...**" > log.txt
        if grep -q "config.dev.yml" trufflehog.json; then
          echo "âŒ TruffleHog found issues in config.dev.yml" >> log.txt
        else
          echo "âœ… No issues found in config.dev.yml" >> log.txt
        fi
        echo "ðŸ” **Checking config.prod.yml for sensitive data...**" >> log.txt
        if grep -q "config.prod.yml" trufflehog.json; then
          echo "âŒ TruffleHog found issues in config.prod.yml" >> log.txt
        else
          echo "âœ… No issues found in config.prod.yml" >> log.txt
        fi

    - name: Add result as comment
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: sensitive
        recreate: true
        path: log.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}